import React from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return React.createElement(
    'html',
    { lang: 'en' },
    React.createElement('head', null,
      React.createElement('meta', { charSet: 'UTF-8' }),
      React.createElement('meta', { name: 'viewport', content: 'width=device-width, initial-scale=1.0' }),
      React.createElement('title', null, metadata.title),
      React.createElement('meta', { name: 'description', content: metadata.description }),
    ),
    React.createElement('body', null, children)
  );
};

export default RootLayout;
